HCL-TECH-SOFTWARE/appscan-sdk

.gitignore
pom.xml
src/main/java/com/hcl/appscan/sdk/auth/AuthenticationHandler.java
src/main/java/com/hcl/appscan/sdk/auth/IAuthenticationProvider.java
src/main/java/com/hcl/appscan/sdk/http/HttpClient.java
src/main/java/com/hcl/appscan/sdk/http/HttpPart.java
src/main/java/com/hcl/appscan/sdk/http/HttpResponse.java
src/main/java/com/hcl/appscan/sdk/http/IHttpProgress.java
src/main/java/com/hcl/appscan/sdk/scan/IScanFactory.java
src/main/java/com/hcl/appscan/sdk/scan/IScanManager.java
src/main/java/com/hcl/appscan/sdk/scan/IScanServiceProvider.java
src/main/java/com/hcl/appscan/sdk/scanners/sast/SAClient.java
src/main/java/com/hcl/appscan/sdk/scanners/sast/targets/ICppTarget.java
src/main/java/com/hcl/appscan/sdk/scanners/sast/targets/IDotNetTarget.java
src/main/java/com/hcl/appscan/sdk/scanners/sast/targets/IJEETarget.java
src/main/java/com/hcl/appscan/sdk/scanners/sast/targets/IJavaTarget.java
src/main/java/com/hcl/appscan/sdk/scanners/sast/xml/DOMWriter.java
src/main/java/com/hcl/appscan/sdk/scanners/sast/xml/XmlWriter.java
src/main/java/com/hcl/appscan/sdk/utils/ArchiveUtil.java
src/main/java/com/hcl/appscan/sdk/utils/ServiceUtil.java
src/main/java/com/hcl/appscan/sdk/utils/SystemUtil.java

Fixes javadoc issues and updates the pom.xml for publishing to Maven Central.

prepare for publish to Maven Central

---

src/main/java/com/hcl/appscan/sdk/CoreConstants.java
src/main/java/com/hcl/appscan/sdk/results/CloudResultsProvider.java
src/main/java/com/hcl/appscan/sdk/results/NonCompliantIssuesResultProvider.java

Adding checking report status before download.

ASA-1724 Jenkins Plugin Scan Report Results Link

---

src/main/java/com/hcl/appscan/sdk/scanners/sast/SAClient.java

ASA-1784: Adding a way to check if major version changed

ASA-1784: Adding a way to check if major version changed

---

src/main/java/com/hcl/appscan/sdk/scanners/sast/SAClient.java
src/main/java/com/hcl/appscan/sdk/scanners/sast/SASTConstants.java

ASA-2035: add env var for client version

ASA-2035: add env var for client version

---

src/main/java/com/hcl/appscan/sdk/scanners/sast/SAClient.java
src/main/java/com/hcl/appscan/sdk/scanners/sast/SASTConstants.java

ASA-2029: Adding plugin tool version (Eclipse IDE, IntelliJ IDE, VS IDE, Jenkins, Maven, etc) as a stat

ASA-2029: Adding plugin tool version as a stat

---

src/main/java/com/hcl/appscan/sdk/CoreConstants.java
src/main/java/com/hcl/appscan/sdk/scan/ASEScanServiceProvider.java

Updated the traffic file upload parameter name  from "filetoUpload" to "uploadedfile"  in ASE-Jenkins code base.

ASE-2120 changes

---

src/main/java/com/hcl/appscan/sdk/CoreConstants.java
src/main/java/com/hcl/appscan/sdk/results/CloudResultsProvider.java
src/main/java/com/hcl/appscan/sdk/results/NonCompliantIssuesResultProvider.java
src/main/java/com/hcl/appscan/sdk/scan/CloudScanServiceProvider.java

Updating Jenkins Console Log if Scan fails in ASOC

ASA-2002 Jenkins Job should Fail If Scan Fails in ASOC

---

src/main/java/com/hcl/appscan/sdk/messages.properties
src/main/java/com/hcl/appscan/sdk/scanners/sast/SAClient.java
src/main/java/com/hcl/appscan/sdk/scanners/sast/SASTConstants.java

ASA-2245: fixing NPE when starting up and server unreachable

ASA-2245: fixing NPE when starting up and server unreachable

---

src/main/java/com/hcl/appscan/sdk/scan/CloudScanServiceProvider.java

503 error handling using try catch

---

src/main/java/com/hcl/appscan/sdk/scanners/dynamic/DASTScan.java

ASA-4007(master slave configuration issue)

---

src/main/java/com/hcl/appscan/sdk/CoreConstants.java
src/main/java/com/hcl/appscan/sdk/scanners/sast/SAClient.java
src/main/java/com/hcl/appscan/sdk/utils/ServiceUtil.java

ASA 6609 & ASA 6586

---

src/main/java/com/hcl/appscan/sdk/CoreConstants.java
src/main/java/com/hcl/appscan/sdk/scanners/sast/SAClient.java
src/main/java/com/hcl/appscan/sdk/utils/ServiceUtil.java

* ASA-6609
* ASA-6609
* Update SAClient.java
* Update ServiceUtil.java

ASA-6609 & ASA-6586 (#88)

---

src/main/java/com/hcl/appscan/sdk/scan/CloudScanServiceProvider.java
src/main/java/com/hcl/appscan/sdk/scanners/dynamic/DASTConstants.java
src/main/java/com/hcl/appscan/sdk/utils/FileUtil.java

* ASA-6774
Able to execute DAST scan using .scan, .scant, and recorded login files.

ASA-6774 (#100)

---

src/main/java/com/hcl/appscan/sdk/utils/ArchiveUtil.java

Remove the .git folder from the zip file

Remove the .git folder from the zip file

---

src/main/java/com/hcl/appscan/sdk/scanners/sast/SAClient.java
src/main/java/com/hcl/appscan/sdk/scanners/sast/SASTScan.java

It is being done to handle the "ASA-2774" Jira task.

Changed the name of the generated IRX file (#107)

---

src/main/java/com/hcl/appscan/sdk/scan/ASEScanServiceProvider.java

ASPL-532
Better message to be conveyed in Jenkins console when traffic file > 200Mb is uploaded

ASPL-532 (#111)

---

src/main/java/com/hcl/appscan/sdk/CoreConstants.java
src/main/java/com/hcl/appscan/sdk/messages.properties
src/main/java/com/hcl/appscan/sdk/scanners/dynamic/DASTScan.java
src/main/java/com/hcl/appscan/sdk/utils/ServiceUtil.java

URL validity check for DAST scans.
Update ServiceUtil.java

ASA 2762 (#112)

---

src/main/java/com/hcl/appscan/sdk/messages.properties
src/main/java/com/hcl/appscan/sdk/scan/CloudScanServiceProvider.java
src/main/java/com/hcl/appscan/sdk/scanners/dynamic/DASTScan.java

Error message for the invalid URL has been updated.

updated the error message

---

src/main/java/com/hcl/appscan/sdk/CoreConstants.java
src/main/java/com/hcl/appscan/sdk/scan/CloudScanServiceProvider.java

Addressing the review comments

Suggested changes

---

src/main/java/com/hcl/appscan/sdk/scan/CloudScanServiceProvider.java

Execution of SCA scan if the OSO option is checked (#137)

---

src/main/java/com/hcl/appscan/sdk/CoreConstants.java

Personal scan support: ASA-8329.

personal scan support in Jenkins plugin (#150)

---

src/main/java/com/hcl/appscan/sdk/CoreConstants.java
src/main/java/com/hcl/appscan/sdk/utils/ServiceUtil.java

https://jira02.hclpnp.com/browse/ASA-8557

API change SCX to v4 (#152)

---

src/main/java/com/hcl/appscan/sdk/CoreConstants.java
src/main/java/com/hcl/appscan/sdk/scanners/sast/SAClient.java
src/main/java/com/hcl/appscan/sdk/scanners/sast/SASTConstants.java
src/main/java/com/hcl/appscan/sdk/scanners/sast/SASTScanManager.java
src/main/java/com/hcl/appscan/sdk/scanners/sast/SAST_SCA_Scan.java
src/main/java/com/hcl/appscan/sdk/utils/ServiceUtil.java

This commit does 2 things:
1. Only creates an SCA scan if the user has entitlement.
2. Ensures that the SAClientUtil is downloaded from the url specified by the serviceUrl option and that the correct public key is retrieved for encrypting the .irx.

only run SCA scan if user has entitlement and get correct public key

---

src/main/java/com/hcl/appscan/sdk/CoreConstants.java
src/main/java/com/hcl/appscan/sdk/messages.properties
src/main/java/com/hcl/appscan/sdk/results/ASEResultsProvider.java
src/main/java/com/hcl/appscan/sdk/scan/ASEScanServiceProvider.java
src/main/java/com/hcl/appscan/sdk/scan/ASEScanType.java
src/main/java/com/hcl/appscan/sdk/utils/ServiceUtil.java

Implementation of AppScan Enterprise Postman collection.

ASPL-836: ASE Postman Collection
